//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerInformation
    {
        public int DealerId { get; set; }
        public int LocationId { get; set; }
        public string DealerAddress { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    }
}
