//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransmissionLookup
    {
        public int TransmissionId { get; set; }
        public string TransmissionType { get; set; }
    }
}
