//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserServiceOrderDetail
    {
        public int ServiceOrderId { get; set; }
        public int UserId { get; set; }
        public int VehicleId { get; set; }
        public int DealerId { get; set; }
        public string ServicesOpted { get; set; }
        public string Comments { get; set; }
        public int Status { get; set; }
        public int ScheduleId { get; set; }
        public System.DateTime ScheduleDetails { get; set; }
    }
}
